int pinG=8;
int pinF=9;
int pinA=6;
int pinB=5;
int pinE=4;
int pinD=3;
int pinC=2;
int pinDP=7;

void setup() {  
  pinMode(pinG, OUTPUT);
  pinMode(pinF, OUTPUT);
  pinMode(pinA, OUTPUT);
  pinMode(pinB, OUTPUT);
  pinMode(pinE, OUTPUT);
  pinMode(pinD, OUTPUT);
  pinMode(pinC, OUTPUT);
  pinMode(pinDP, OUTPUT);
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(pinG, LOW);
  digitalWrite(pinF, HIGH);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, HIGH);
  digitalWrite(pinD, HIGH);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, LOW);
  delay(1000);
  digitalWrite(pinG, LOW);
  digitalWrite(pinF, LOW);
  digitalWrite(pinA, LOW);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, LOW);
  digitalWrite(pinD, LOW);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, HIGH);
  delay(1000);
  digitalWrite(pinG, HIGH);
  digitalWrite(pinF, LOW);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, HIGH);
  digitalWrite(pinD, HIGH);
  digitalWrite(pinC, LOW);
  digitalWrite(pinDP, LOW);
  delay(1000);
  digitalWrite(pinG, HIGH);
  digitalWrite(pinF, LOW);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, LOW);
  digitalWrite(pinD, HIGH);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, HIGH);
  delay(1000);
  digitalWrite(pinG, HIGH);
  digitalWrite(pinF, HIGH);
  digitalWrite(pinA, LOW);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, LOW);
  digitalWrite(pinD, LOW);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, LOW);
  delay(1000);
  digitalWrite(pinG, HIGH);
  digitalWrite(pinF, HIGH);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, LOW);
  digitalWrite(pinE, LOW);
  digitalWrite(pinD, HIGH);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, HIGH);
  delay(1000);
  digitalWrite(pinG, HIGH);
  digitalWrite(pinF, HIGH);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, LOW);
  digitalWrite(pinE, HIGH);
  digitalWrite(pinD, HIGH);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, LOW);
  delay(1000);
  digitalWrite(pinG, LOW);
  digitalWrite(pinF, HIGH);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, LOW);
  digitalWrite(pinD, LOW);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, HIGH);
  delay(1000);
  digitalWrite(pinG, HIGH);
  digitalWrite(pinF, HIGH);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, HIGH);
  digitalWrite(pinD, HIGH);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, LOW);  
  delay(1000);
  digitalWrite(pinG, HIGH);
  digitalWrite(pinF, HIGH);
  digitalWrite(pinA, HIGH);
  digitalWrite(pinB, HIGH);
  digitalWrite(pinE, LOW);
  digitalWrite(pinD, HIGH);
  digitalWrite(pinC, HIGH);
  digitalWrite(pinDP, HIGH);
  delay(1000);
}
